In [20]:
import pandas as pd 
import matplotlib.pyplot as plt
import ta
import numpy
import os

In [21]:

df = pd.read_excel(r"C:\Users\nextrow\OneDrive - NextRow Inc\Desktop\AGENTS\Stock_prediction\Stock_prediction\stock-ai-system\data\raw\market_data\indian_stocks.xlsx", sheet_name=None)

In [22]:
def sort_data(stock_df):
    stock_df = stock_df.sort_values(["date"])
  
    return stock_df

In [23]:
def add_indicators(stock_df):
    stock_df["sma_7"]=stock_df["close"].rolling(window=7).mean()
    stock_df["sma_20"]=stock_df["close"].rolling(window=20).mean()
    stock_df["sma_50"]=stock_df["close"].rolling(window=50).mean()
    stock_df["ema_9"]=stock_df["close"].ewm(span=9,adjust=False).mean()
    stock_df["ema_21"]=stock_df["close"].ewm(span=21,adjust=False).mean()
    stock_df["ema_50"]=stock_df["close"].ewm(span=50,adjust=False).mean()
    stock_df['macd']=ta.trend.MACD(stock_df['close']).macd()
    stock_df['rsi']=ta.momentum.RSIIndicator(stock_df['close']).rsi()
    stock_df['bollinger_bands_upper'] = ta.volatility.BollingerBands(stock_df["close"]).bollinger_hband()
    stock_df['bollinger_bands_lower'] = ta.volatility.BollingerBands(stock_df["close"]).bollinger_lband()

    return stock_df

In [24]:

stock_df=[]
for symbol,data in df.items():
    data_sorted = sort_data(data)
    stock_df.append(add_indicators(data_sorted))
stock_df=pd.concat(stock_df,ignore_index=True)

In [25]:
print(stock_df.groupby("stock")["close"].mean().describe())
print("\nTop 10 highest priced stocks:")
print(stock_df.groupby("stock")["close"].mean().sort_values(ascending=False).head(10))
print("\nBottom 10 lowest priced stocks:")
print(stock_df.groupby("stock")["close"].mean().sort_values().head(10))

count      339.000000
mean      1409.077936
std       5238.628121
min         13.817571
25%        205.674782
50%        530.739826
75%       1175.986655
max      81535.954259
Name: close, dtype: float64

Top 10 highest priced stocks:
stock
MRF           81535.954259
PAGEIND       29668.886698
HONAUT        29634.270670
SHREECEM      21809.385567
BOSCHLTD      20484.770912
MARUTI         8279.752644
ULTRACEMCO     6281.139867
BAJAJHLDNG     5021.177977
DIXON          4944.861637
OFSS           4569.059366
Name: close, dtype: float64

Bottom 10 lowest priced stocks:
stock
KELLTONTEC    13.817571
BCG           15.180545
SOUTHBANK     17.087708
EASEMYTRIP    18.382431
SUZLON        19.574019
TRIDENT       20.015069
IDEA          22.469592
MTNL          23.436633
IOB           25.933746
IRB           26.065932
Name: close, dtype: float64

In [26]:
stock_df["date"] = pd.to_datetime(stock_df["date"])
stock_df["time_idx"]=stock_df.groupby("stock").cumcount()
stock_df.head()

,date,open,high,low,close,volume,stock,sma_7,sma_20,sma_50,ema_9,ema_21,ema_50,macd,rsi,bollinger_bands_upper,bollinger_bands_lower,time_idx
0,2015-11-23,212.88,214.65,212.03,213.72,10710408,RELIANCE,NaN,NaN,NaN,213.720000,213.720000,213.720000,NaN,NaN,NaN,NaN,0
1,2015-11-24,213.55,217.72,213.12,216.85,15103570,RELIANCE,NaN,NaN,NaN,214.346000,214.004545,213.842745,NaN,NaN,NaN,NaN,1
2,2015-11-26,217.59,222.28,216.97,221.54,24283988,RELIANCE,NaN,NaN,NaN,215.784800,214.689587,214.144598,NaN,NaN,NaN,NaN,2
3,2015-11-27,221.62,222.40,218.28,219.39,11110636,RELIANCE,NaN,NaN,NaN,216.505840,215.116897,214.350300,NaN,NaN,NaN,NaN,3
4,2015-11-30,219.27,220.59,215.64,216.43,30520156,RELIANCE,NaN,NaN,NaN,216.490672,215.236270,214.431857,NaN,NaN,NaN,NaN,4

In [27]:
stock_df

,date,open,high,low,close,volume,stock,sma_7,sma_20,sma_50,ema_9,ema_21,ema_50,macd,rsi,bollinger_bands_upper,bollinger_bands_lower,time_idx
0,2015-11-23,212.88,214.65,212.03,213.72,10710408,RELIANCE,NaN,NaN,NaN,213.720000,213.720000,213.720000,NaN,NaN,NaN,NaN,0
1,2015-11-24,213.55,217.72,213.12,216.85,15103570,RELIANCE,NaN,NaN,NaN,214.346000,214.004545,213.842745,NaN,NaN,NaN,NaN,1
2,2015-11-26,217.59,222.28,216.97,221.54,24283988,RELIANCE,NaN,NaN,NaN,215.784800,214.689587,214.144598,NaN,NaN,NaN,NaN,2
3,2015-11-27,221.62,222.40,218.28,219.39,11110636,RELIANCE,NaN,NaN,NaN,216.505840,215.116897,214.350300,NaN,NaN,NaN,NaN,3
4,2015-11-30,219.27,220.59,215.64,216.43,30520156,RELIANCE,NaN,NaN,NaN,216.490672,215.236270,214.431857,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747094,2025-11-17,63.01,64.50,62.73,63.14,213537,ONMOBILE,63.964286,69.5130,65.9280,65.459524,67.402801,65.563594,-1.095918,36.910361,78.190876,60.835124,2472
747095,2025-11-18,63.14,64.31,62.00,62.25,204599,ONMOBILE,63.557143,69.1090,66.1032,64.817620,66.934365,65.433649,-1.338171,34.982814,78.332307,59.885693,2473
747096,2025-11-19,62.31,62.90,60.72,62.24,211687,ONMOBILE,63.291429,68.6660,66.2876,64.302096,66.507604,65.308408,-1.513517,34.960722,78.305928,59.026072,2474
747097,2025-11-20,61.20,61.79,59.12,59.81,281733,ONMOBILE,62.794286,68.0675,66.4210,63.403677,65.898731,65.092784,-1.827495,30.002506,78.326240,57.808760,2475
747098,2025-11-21,59.32,59.79,57.57,57.97,136825,ONMOBILE,61.775714,67.3020,66.5024,62.316941,65.177937,64.813459,-2.199444,26.892427,78.158135,56.445865,2476

In [28]:
stock_df.isna().sum()

date                         0
open                         0
high                         0
low                          0
close                        0
volume                       0
stock                        0
sma_7                     2034
sma_20                    6441
sma_50                   16611
ema_9                        0
ema_21                       0
ema_50                       0
macd                      8475
rsi                       4407
bollinger_bands_upper     6441
bollinger_bands_lower     6441
time_idx                     0
dtype: int64

In [29]:
stock_df.dropna(inplace=True)

In [30]:
stock_df.isna().sum()

date                     0
open                     0
high                     0
low                      0
close                    0
volume                   0
stock                    0
sma_7                    0
sma_20                   0
sma_50                   0
ema_9                    0
ema_21                   0
ema_50                   0
macd                     0
rsi                      0
bollinger_bands_upper    0
bollinger_bands_lower    0
time_idx                 0
dtype: int64

In [31]:
train_list, val_list, test_list = [], [], []

for stock, group in stock_df.groupby("stock"):
    group = group.sort_values("date")
    
    train_list.append(group[group["date"] <= "2023-06-30"])
    val_list.append(group[(group["date"] > "2023-06-30") & (group["date"] <= "2024-06-30")])
    test_list.append(group[group["date"] > "2024-06-30"])

train      = pd.concat(train_list).reset_index(drop=True)
validation = pd.concat(val_list).reset_index(drop=True)
test       = pd.concat(test_list).reset_index(drop=True)

print("Train:", train["date"].min(), "→", train["date"].max())
print("Val:  ", validation["date"].min(), "→", validation["date"].max())
print("Test: ", test["date"].min(), "→", test["date"].max())
print("Train stocks:", train["stock"].nunique())
print("Val stocks:  ", validation["stock"].nunique())
print("Test stocks: ", test["stock"].nunique())
print("Train rows:", len(train))
print("Val rows:  ", len(validation))
print("Test rows: ", len(test))

Train: 2016-02-03 00:00:00 → 2023-06-30 00:00:00
Val:   2023-07-03 00:00:00 → 2024-06-28 00:00:00
Test:  2024-07-01 00:00:00 → 2025-11-21 00:00:00
Train stocks: 331
Val stocks:   339
Test stocks:  339
Train rows: 529946
Val rows:   82801
Test rows:  117741

In [32]:

train_stocks = set(train["stock"].unique())


validation = validation[validation["stock"].isin(train_stocks)].reset_index(drop=True)
test = test[test["stock"].isin(train_stocks)].reset_index(drop=True)


all_stocks = set(stock_df["stock"].unique())
removed = all_stocks - train_stocks
print("Removed stocks:", removed)
print("Remaining stocks:", len(train_stocks))

Removed stocks: {'BHARTIHEXA', 'YATRA', 'TATATECH', 'JIOFIN', 'LLOYDSME', 'REDTAPE', 'RRKABEL', 'MANKIND'}
Remaining stocks: 331

In [33]:
from pytorch_forecasting import TimeSeriesDataSet
from pytorch_forecasting.data import GroupNormalizer
import pickle
training = TimeSeriesDataSet(
    train,
    time_idx="time_idx",
    target="close",
    group_ids=["stock"],
    max_encoder_length=60,
    max_prediction_length=7,
    static_categoricals=["stock"],
    time_varying_unknown_reals=[
        'open', 'high', 'low', 'close', 'volume',
        'sma_7', 'sma_20', 'sma_50',
        'ema_9', 'ema_21', 'ema_50',
        'macd', 'rsi',
        'bollinger_bands_upper', 'bollinger_bands_lower'
    ],
    target_normalizer=GroupNormalizer(groups=["stock"], transformation="softplus"),
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)

with open(r"C:\Users\nextrow\OneDrive - NextRow Inc\Desktop\AGENTS\Stock_prediction\Stock_prediction\stock-ai-system\ml_models\technical_prediction\training_dataset.pkl", "wb") as f:
    pickle.dump(training, f)
size = os.path.getsize(r"C:\Users\nextrow\OneDrive - NextRow Inc\Desktop\AGENTS\Stock_prediction\Stock_prediction\stock-ai-system\ml_models\technical_prediction\training_dataset.pkl")/1024/1024
print(f"✅ Saved: {size:.1f} MB")

c:\anaconda\envs\secondenv\Lib\site-packages\pytorch_forecasting\data\timeseries.py:1282: UserWarning: Min encoder length and/or min_prediction_idx and/or min prediction length and/or lags are too large for 1 series/groups which therefore are not present in the dataset index. This means no predictions can be made for those series. First 10 removed groups: [{'__group_id__stock': '3IINFOLTD'}]
  warnings.warn(

✅ Saved: 83.6 MB

In [34]:
#datasets
testing = TimeSeriesDataSet.from_dataset(training,test,predict=True)
validating = TimeSeriesDataSet.from_dataset(training,validation,predict=True)

c:\anaconda\envs\secondenv\Lib\site-packages\pytorch_forecasting\data\timeseries.py:1188: UserWarning: If predicting, no randomization should be possible - setting stop_randomization=True
  warnings.warn(
c:\anaconda\envs\secondenv\Lib\site-packages\pytorch_forecasting\data\timeseries.py:1188: UserWarning: If predicting, no randomization should be possible - setting stop_randomization=True
  warnings.warn(

In [35]:
#data loaders

training_dataloader   = training.to_dataloader(train=True,  batch_size=256, num_workers=2)
validation_dataloader = validating.to_dataloader(train=False, batch_size=256, num_workers=2)
testing_dataloader    = testing.to_dataloader(train=False,  batch_size=256, num_workers=2)

In [36]:
from pytorch_forecasting import TemporalFusionTransformer
from pytorch_forecasting.metrics.quantile import QuantileLoss
tft = TemporalFusionTransformer.from_dataset(
    training,
    hidden_size=64,
    attention_head_size=4,
    dropout=0.1,
    hidden_continuous_size=32,
    learning_rate=0.003,          
    loss=QuantileLoss(),
    log_interval=10,
    reduce_on_plateau_patience=3   
)

c:\anaconda\envs\secondenv\Lib\site-packages\lightning\pytorch\utilities\parsing.py:208: Attribute 'loss' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['loss'])`.
c:\anaconda\envs\secondenv\Lib\site-packages\lightning\pytorch\utilities\parsing.py:208: Attribute 'logging_metrics' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['logging_metrics'])`.
c:\anaconda\envs\secondenv\Lib\site-packages\pytorch_forecasting\models\temporal_fusion_transformer\__init__.py:143: UserWarning: In pytorch-forecasting models, on versions 1.1.X, the default optimizer defaults to 'adam', if pytorch_optimizer is not installed, otherwise it defaults to 'ranger' from pytorch_optimizer. From version 1.2.0, the default optimizer will be 'adam' regardless of whether pytorch_optimizer is installed, in order to minimize the number of dependencies in default parameter settings. Users who wish to ensure their code continues using 'ranger' as optimizer should ensure that pytorch_optimizer is installed, and set the optimizer parameter explicitly to 'ranger'.
  super().__init__(loss=loss, logging_metrics=logging_metrics, **kwargs)

In [37]:
from lightning.pytorch.callbacks import Callback, ModelCheckpoint

class EpochLogger(Callback):
    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
        if batch_idx % 100 == 0:
            loss = outputs['loss'].item()
            print(f"Epoch {trainer.current_epoch+1} | Batch {batch_idx} | train_loss: {loss:.4f}")

    def on_train_epoch_end(self, trainer, pl_module):
        train_loss = trainer.callback_metrics.get('train_loss_epoch', 0)
        val_loss = trainer.callback_metrics.get('val_loss', 0)
        print(f"\n Epoch {trainer.current_epoch+1}/30 | train_loss: {train_loss:.4f} | val_loss: {val_loss:.4f}\n")

checkpoint_callback = ModelCheckpoint(
    monitor="val_loss",
    dirpath="/kaggle/working/tft_checkpoints/",  
    filename="tft-best",
    save_top_k=1,
    mode="min"
)

In [38]:
from lightning.pytorch import Trainer
trainer = Trainer(
    max_epochs=50,            
    accelerator="gpu",
    devices=1,
    gradient_clip_val=0.1,
    enable_progress_bar=False,
    callbacks=[EpochLogger(), checkpoint_callback]
)

trainer.fit(tft, training_dataloader, validation_dataloader)

MisconfigurationException: No supported gpu backend found!